version: "3.7"

services:
  reactavancado-web:
    container_name: reactavancado-web
    build:
      context: ../
      dockerfile: ./docker/dockerfile
      target: development
    command: yarn start
    ports:
      - "3011:3000"
    volumes:
      - ../src:/usr/src/reactavancado-web/src
      - ../public:/usr/src/reactavancado-web/public
      - ../tsconfig.json:/usr/src/reactavancado-web/tsconfig.json
